name: Deploy Backend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" | base64 -d > mykey.pem
          chmod 600 mykey.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i mykey.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/${{ secrets.SERVER_USER }}/my-backend &&
            git pull &&
            docker stop mybackend || true &&
            docker rm mybackend || true &&
            docker pull yaseenshaik23/my-backend:1.0 &&
            docker run -d -p 3000:3000 --name mybackend yaseenshaik23/my-backend:1.0
          "
